# Generated by Django 3.2.1 on 2022-02-11 06:26

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220210_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.ImageField(default='users/default.png', upload_to=account.models.get_image)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='drugs',
            field=models.ManyToManyField(related_name='profession', to='account.Drug'),
        ),
    ]
