# Generated by Django 3.2.1 on 2022-02-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220212_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnos',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
