# Generated by Django 3.2.1 on 2022-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_diagnos_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='diagnos',
        ),
        migrations.RemoveField(
            model_name='category',
            name='drugs',
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('drugs', models.ManyToManyField(related_name='drugs', to='account.Drug')),
            ],
        ),
        migrations.AddField(
            model_name='diagnos',
            name='disease',
            field=models.ManyToManyField(related_name='disease', to='account.Disease'),
        ),
    ]
