# Generated by Django 3.2.1 on 2022-03-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220212_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
