# Generated by Django 3.2.1 on 2022-03-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220302_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='image',
        ),
    ]
