# Generated by Django 3.2.1 on 2022-03-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20220325_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fctoken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.version'),
        ),
    ]
