# Generated by Django 3.2.1 on 2022-03-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particpaint',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='particpaintThread', to='chat.thread'),
        ),
    ]
