# Generated by Django 3.2.1 on 2022-03-09 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220302_1453'),
        ('schedule', '0002_schedule_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_profession', to='account.profession'),
        ),
    ]
